#! /bin/bash

[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
	# Fall back to using the very slow lsb_release utility
	DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi
echo
echo "### Distro information ###"
printf "Linux.Distro=\"%s\"\nLinux.Release=%s\"\n" "$DISTRIB_DESCRIPTION" "$(uname -r)"
echo
echo "### System uptime ###"
uptime=$(uptime --pretty)
echo -e System.uptime=\"${uptime#up }\"
echo
echo "### Root Filesystem ####"
printf "{\n\t\"Device\":\t\"%s\",\n\t\"Capacity\":\t\"%s\",\n\t\"Used\":\t\t\"%s\",\n\t\"Available\":\t\"%s\",\n\t\"Usage\":\t\"%s\"\n}\n" $(df -h / |tail -n+2|head -n1 | awk '{print $1,$2,$3,$4,$5}')
echo "### RAM USAGE ####"
printf "{\n\t\"Total\":\t\"%s\",\n\t\"Used\":\t\t\"%s\",\n\t\"Free\":\t\t\"%s\",\n\t\"Shared\":\t\"%s\",\n\t\"Buffered\":\t\"%s\",\n\t\"Available\":\t\"%s\"\n}\n" $(free -ht | tail -n+2 | grep Mem: | awk '{print $2,$3,$4,$5,$6,$7}')
echo
[[ -n "$SSH_CLIENT" ]] && echo "### SSH connection ###" && printf "{\n\t\"SSHClientAddress\":\"%s,\"\n\t\"SSHClientTTY\":\t\"%s\"\n}\n" ${SSH_CLIENT%% *} ${SSH_TTY}; 
echo "### Established connections###"
ss -lt4o state established  2>/dev/null | tail -n+2 | awk '{print $3,$4}' | column -t

